---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: quarterly
    commit-message:
      prefix: chore

  - package-ecosystem: maven
    directory: "/spring-boot"
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: "nginx/oauth2/e2e"
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
    commit-message:
      prefix: chore
