---
services:
  prometheus:
    image: docker.io/prom/prometheus:v3.9.1
    volumes:
      - ./etc/prometheus:/etc/prometheus:ro
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - "9090:9090"

  kafbat:
    image: docker.io/kafbat/kafka-ui:v1.4.2
    ports:
      - "8081:8080"
    environment:
      DYNAMIC_COONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"

  # https://docs.confluent.io/platform/current/installation/docker/config-reference.html
  # https://developer.confluent.io/confluent-tutorials/kafka-on-docker/
  kafka:
    # https://docs.confluent.io/platform/current/release-notes/changelog.html
    image: docker.io/confluentinc/cp-kafka:8.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "iiHp29bDRDyXDukBBU9oGQ"

  service:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "kafka:29092"
